"make dist" will honor CHECK_SYNTAX=false
svn path=/branches/SuSE-SLE-10-SP1-Branch/devtools/; revision=33331

diff --git a/devtools/admin/Makefile.am.common b/devtools/admin/Makefile.am.common
--- a/devtools/admin/Makefile.am.common
+++ b/devtools/admin/Makefile.am.common
@@ -29,7 +29,19 @@ NEWDEP=${top_builddir}/.dep.new
 
 dist-hook: check-syntax
 
+CHECK_SYNTAX = true
 check-syntax: $(client_DATA) $(ycpchook)
-	if test "$(client_DATA)"; then $(bindir)/ycpc -qE -M. -I. $(YCPCFLAGS) $(filter %.ycp,$^) || exit 1; fi
+	@if test "$(client_DATA)"; then \
+	  if $(CHECK_SYNTAX); then \
+	    TO_CHECK="$(filter %.ycp,$^)"; \
+	    echo "Checking syntax of $${TO_CHECK}"; \
+	    if ! $(YCPC) -qE -M. -I. $(YCPCFLAGS) $${TO_CHECK}; then \
+	      echo "Failed. Disable by 'make ... CHECK_SYNTAX=false' at your own risk"; \
+	      exit 1; \
+	    fi; \
+	  else \
+	    echo "Syntax check disabled"; \
+	  fi; \
+	fi
 
 -include .dep
