fix notes by @mvidner

diff --git a/ytools/y2tool/find-unused-published b/ytools/y2tool/find-unused-published
--- a/ytools/y2tool/find-unused-published
+++ b/ytools/y2tool/find-unused-published
@@ -2,10 +2,13 @@
 # Assist in API cleanup by finding published ("global") functions/variables
 # that are not used by other code.
 #
-# Usage:
-# cd [a clean checkout of all yast repositories]
-# MODULE_RB=yast2/library/network/src/modules/NetworkPopup.rb
-# find-unused-published $MODULE_RB
+
+usage() {
+    echo "Usage:
+    cd [a clean checkout of all yast repositories]
+    find-unused-published yast2/library/network/src/modules/NetworkPopup.rb" >&2
+}
+
 
 # $1 YaST Module in Ruby, pathname
 published() {
@@ -24,19 +27,13 @@ find_unused() {
     done
 }
 
-usage() {
-    echo "Usage:
-    cd [a clean checkout of all yast repositories]
-    find-unused-published yast2/library/network/src/modules/NetworkPopup.rb" >&2
-}
-
 if [ $# -ne 1 ]; then
     usage
     exit 1
 fi
 
 if [ ! -f $1 ]; then
-    echo "ERROR: File do not exist" >&2
+    echo "ERROR: File '$1' do not exist" >&2
     usage
     exit 2
 fi
